baseURL: ""
# Disable taxonomy pages (disables categories and tags folders)
params:
  logo: "/img/logo.png"
disableKinds:
- taxonomy
- taxonomyTerm
# for xml output
languageCode: "en-uk"
# for website
defaultContentLanguage: "en-uk"
languages:
  en-au:
    weight: 1
  en-uk:
    weight: 2
 
title: 
# alternate copyright company text
copyright: SociableGeeks Photography
# controls number of pages displayed on list pages
paginate: 5
# controls the summary length on list pages
summaryLength: 7

# menu links via config file
menu:
  main:
  - name: About
    url: /index.html
    weight: 19

  - name: Instagram
    url: http://www.instagram.com/sociablegeeksphotography
    weight: 20
    params:
      blank: true
  
  - name: Facebook
    url: https://www.facebook.com/sociablegeeksphotography
    weight: 21
    params:
      blank: true