baseURL: ""
# Disable taxonomy pages (disables categories and tags folders)
disableKinds:
- taxonomy
- taxonomyTerm
# for xml output
languageCode: "en-uk"
# for website
defaultContentLanguage: "en-uk"
languages:
  en-uk:
    weight: 1
 
title: 
# alternate copyright company text
copyright: SociableGeeks Photography
# controls number of pages displayed on list pages
paginate: 5
# controls the summary length on list pages
summaryLength: 7

# menu links via config file
menu:
  main:
  - name: About
    url: /index.html
    weight: 20

# ðŸ‘‡ ALL parameters are now combined in this single block ðŸ‘‡
params:
  # This is the logo path your theme expects
  logo: "/img/logo.png"

  # These are your social media icons
  social:
    - name: "Instagram"
      icon: "fa-brands fa-instagram"
      url: "https://instagram.com/sociablegeeksphotography"
    
    - name: "Facebook"
      icon: "fa-brands fa-facebook"
      url: "https://www.facebook.com/sociablegeeksphotography"

    - name: "Mail"
      icon: "fa-regular fa-envelope"
      url: "mailto:sociablegeeksphotography@gmail.com"
